name: 'Pull Request Validation'

on: 
  pull_request:

jobs:
  slack-module:
    name: Slack Module Tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, macOS-10.14, ubuntu-18.04]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester Module
      run: .\.github\workflows\Install-PesterModule.ps1
      shell: pwsh
    - name: Run Pester Tests
      env:
        SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
        SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
      run: .\.github\workflows\Invoke-PesterTests.ps1
      shell: pwsh
    - name: Publish Pester Test Results
      if: always()
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_PR_URI: ${{github.event.pull_request._links.comments.href}}
      run: .\.github\workflows\Publish-PesterTests.ps1
      shell: pwsh
    - uses: actions/upload-artifact@master
      with:
        name: Pester Tests ${{matrix.os}}
        path: ./.github/workflows/Slack.Tests.xml
  Context Dump:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  