name: 'Pull Request Validation'

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  pslickpslack-module:
    name: PSlickPSlack PowerShell Module Test and Deploy
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester Module
      run: .\.github\workflows\Install-PesterModule.ps1
      shell: pwsh
    - name: Run Pester Tests
      env:
        SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
        SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
      run: .\.github\workflows\Invoke-PesterTests.ps1
      shell: pwsh
    - name: Seeing env variables
      run: echo ${{github.event}} ${{github.ref}}
    - name: Deploy to PSGallery
      if: github.event_name == 'push' && github.ref == 'master'
      run: echo You would deploy!