name: 'Pull Request Validation'

on: pull_request

jobs:
  Test:
    name: Test
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester Module
      run: .\.github\workflows\Install-PesterModule.ps1
      shell: pwsh
    - name: Run Pester Tests
      run: .\.github\workflows\Invoke-PesterTests.ps1
      shell: pwsh