name: 'Release Validation'

on: 
  release:
    types: [published, prereleased]
jobs:
  pslickpslack-module:
    name: PSlickPSlack Module Deployment
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester Module
      run: .\.github\workflows\Install-PesterModule.ps1
      shell: pwsh
    - name: Run Pester Tests
      env:
        SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
        SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
      run: .\.github\workflows\Invoke-PesterTests.ps1
      shell: pwsh
    - name: Deploy to PSGallery
      if: success()
      run: echo deploy!