name: 'Release Validation'

on: 
  release:
    types: published
jobs:
  pslickpslack-module-1:
    name: PSlickPSlack Module Tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, macOS-10.14, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester Module
      run: .\.github\workflows\Install-PesterModule.ps1
      shell: pwsh
    - name: Run Pester Tests
      env:
        SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
        SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
      run: .\.github\workflows\Invoke-PesterTests.ps1
      shell: pwsh
  pslickpslack-module-2:
    needs: pslickpslack-module-1
    name: PSlickPSlack Module Deployment
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to PSGallery
      env:
        PSGALLERY_TOKEN: ${{secrets.PSGALLERY_TOKEN}}
        RELEASE_NOTES: ${{github.event.release.body}}
        RELEASE_VERSION: ${{github.event.release.tag_name}}
      run: .github\workflows\Deploy-PSlickPSlack.ps1
      shell: pwsh
